services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tastygo-api
    ports:
      - "8081:8080"
    environment:
      - DB_PATH=/data/tastygo.db
      - JWT_SECRET=your_secure_secret_key_change_in_production
      - PORT=8080
      - GIN_MODE=release
    volumes:
      - tastygo-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  tastygo-data:
